import { RAIN_STREET } from "../assets/media";
import type {
  City,
  EventType,
  Incident,
  ReportRow,
  Severity,
  SocialPost,
  VerificationStatus,
} from "./types";

export const CITIES: City[] = [
  { id: "delhi", name: "Delhi", state: "Delhi", lat: 28.6139, lon: 77.209, x: 36.8, y: 28.2 },
  { id: "mumbai", name: "Mumbai", state: "Maharashtra", lat: 19.076, lon: 72.8777, x: 24.2, y: 56.4 },
  { id: "kolkata", name: "Kolkata", state: "West Bengal", lat: 22.5726, lon: 88.3639, x: 66.4, y: 43.8 },
  { id: "chennai", name: "Chennai", state: "Tamil Nadu", lat: 13.0827, lon: 80.2707, x: 47.8, y: 76.5 },
  { id: "bengaluru", name: "Bengaluru", state: "Karnataka", lat: 12.9716, lon: 77.5946, x: 39.2, y: 74.8 },
  { id: "hyderabad", name: "Hyderabad", state: "Telangana", lat: 17.385, lon: 78.4867, x: 43.5, y: 61.5 },
  { id: "ahmedabad", name: "Ahmedabad", state: "Gujarat", lat: 23.0225, lon: 72.5714, x: 22.8, y: 42.2 },
  { id: "jaipur", name: "Jaipur", state: "Rajasthan", lat: 26.9124, lon: 75.7873, x: 30.6, y: 34.4 },
  { id: "lucknow", name: "Lucknow", state: "Uttar Pradesh", lat: 26.8467, lon: 80.9462, x: 46.2, y: 33.8 },
  { id: "patna", name: "Patna", state: "Bihar", lat: 25.5941, lon: 85.1376, x: 56.8, y: 36.6 },
  { id: "guwahati", name: "Guwahati", state: "Assam", lat: 26.1445, lon: 91.7362, x: 78.4, y: 32.4 },
  { id: "bhopal", name: "Bhopal", state: "Madhya Pradesh", lat: 23.2599, lon: 77.4126, x: 36.4, y: 45.8 },
  { id: "nagpur", name: "Nagpur", state: "Maharashtra", lat: 21.1458, lon: 79.0882, x: 42.6, y: 52.2 },
  { id: "visakhapatnam", name: "Visakhapatnam", state: "Andhra Pradesh", lat: 17.6868, lon: 83.2185, x: 55.2, y: 61.8 },
  { id: "kochi", name: "Kochi", state: "Kerala", lat: 9.9312, lon: 76.2673, x: 35.6, y: 86.2 },
  { id: "pune", name: "Pune", state: "Maharashtra", lat: 18.5204, lon: 73.8567, x: 27.4, y: 58.6 },
  { id: "chandigarh", name: "Chandigarh", state: "Chandigarh", lat: 30.7333, lon: 76.7794, x: 35.2, y: 21.6 },
  { id: "srinagar", name: "Srinagar", state: "Jammu and Kashmir", lat: 34.0837, lon: 74.7973, x: 33.8, y: 10.4 },
  { id: "bhubaneswar", name: "Bhubaneswar", state: "Odisha", lat: 20.2961, lon: 85.8245, x: 57.4, y: 52.6 },
  { id: "thiruvananthapuram", name: "Thiruvananthapuram", state: "Kerala", lat: 8.5241, lon: 76.9366, x: 37.4, y: 92.4 },
  { id: "ranchi", name: "Ranchi", state: "Jharkhand", lat: 23.3441, lon: 85.3096, x: 55.6, y: 44.2 },
  { id: "raipur", name: "Raipur", state: "Chhattisgarh", lat: 21.2514, lon: 81.6296, x: 48.8, y: 52.4 },
  { id: "surat", name: "Surat", state: "Gujarat", lat: 21.1702, lon: 72.8311, x: 21.6, y: 48.8 },
  { id: "indore", name: "Indore", state: "Madhya Pradesh", lat: 22.7196, lon: 75.8577, x: 31.2, y: 47.2 },
  { id: "kanpur", name: "Kanpur", state: "Uttar Pradesh", lat: 26.4499, lon: 80.3319, x: 44.6, y: 34.8 },
  { id: "cachar", name: "Cachar", state: "Assam", lat: 24.8333, lon: 92.7789, x: 80.2, y: 38.6 },
  { id: "puri", name: "Puri", state: "Odisha", lat: 19.8135, lon: 85.8312, x: 57.8, y: 55.4 },
];

export const HOME_CITIES = ["delhi", "mumbai", "kolkata", "chennai", "guwahati"] as const;

export const EVENT_META: Record<
  EventType,
  { color: string; bg: string; ring: string; hex: string }
> = {
  "Heavy Rain": { color: "text-sky-600", bg: "bg-sky-50", ring: "ring-sky-200", hex: "#0ea5e9" },
  Flood: { color: "text-cyan-600", bg: "bg-cyan-50", ring: "ring-cyan-200", hex: "#06b6d4" },
  Cyclone: { color: "text-violet-600", bg: "bg-violet-50", ring: "ring-violet-200", hex: "#7c3aed" },
  Heatwave: { color: "text-amber-600", bg: "bg-amber-50", ring: "ring-amber-200", hex: "#f59e0b" },
  "Active Incident": { color: "text-rose-600", bg: "bg-rose-50", ring: "ring-rose-200", hex: "#f43f5e" },
};

export const STATUS_META: Record<VerificationStatus, { cls: string; dot: string }> = {
  Verified: { cls: "bg-emerald-50 text-emerald-700 border-emerald-200", dot: "bg-emerald-500" },
  "Under Review": { cls: "bg-amber-50 text-amber-700 border-amber-200", dot: "bg-amber-500" },
  Unverified: { cls: "bg-rose-50 text-rose-700 border-rose-200", dot: "bg-rose-500" },
};

export const SEVERITY_META: Record<Severity, string> = {
  High: "bg-rose-50 text-rose-600 border-rose-200",
  Medium: "bg-amber-50 text-amber-600 border-amber-200",
  Low: "bg-sky-50 text-sky-600 border-sky-200",
};

export const STATES = [
  "All States",
  "Andhra Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Delhi",
  "Gujarat",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Odisha",
  "Rajasthan",
  "Tamil Nadu",
  "Telangana",
  "Uttar Pradesh",
  "West Bengal",
  "Jammu and Kashmir",
];

const RAIN_IMG = RAIN_STREET;
const FLOOD_IMG =
  "https://images.pexels.com/photos/17609960/pexels-photo-17609960.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200";
const FLOOD2_IMG =
  "https://images.pexels.com/photos/38550996/pexels-photo-38550996.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200";
const STORM_IMG =
  "https://images.pexels.com/photos/17965443/pexels-photo-17965443.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200";
const HEAT_IMG =
  "https://images.pexels.com/photos/19070888/pexels-photo-19070888.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200";

/** Rotating photo pool used by the Reports detail panel (changes on every click). */
export const REPORT_IMAGES: string[] = [RAIN_IMG, FLOOD_IMG, STORM_IMG, FLOOD2_IMG, HEAT_IMG];

export const INCIDENTS: Incident[] = [
  {
    id: "i1",
    type: "Heavy Rain",
    city: "Jaipur",
    state: "Rajasthan",
    minutesAgo: 2,
    status: "Verified",
    severity: "High",
    source: "X (Twitter)",
    aiConfidence: 0.92,
    frequency: 12,
    lat: 26.9124,
    lon: 75.7873,
    description: "Heavy rain continues in Jaipur since morning. Roads are waterlogged and traffic is moving slow.",
    rainfallMm: 86,
  },
  {
    id: "i2",
    type: "Flood",
    city: "Patna",
    state: "Bihar",
    minutesAgo: 5,
    status: "Under Review",
    severity: "High",
    source: "News",
    aiConfidence: 0.88,
    frequency: 8,
    lat: 25.5941,
    lon: 85.1376,
    description: "Flood waters rising near Gandhi Maidan. Several low-lying colonies inundated.",
    rainfallMm: 142,
  },
  {
    id: "i3",
    type: "Heavy Rain",
    city: "Mumbai",
    state: "Maharashtra",
    minutesAgo: 7,
    status: "Verified",
    severity: "Medium",
    source: "X (Twitter)",
    aiConfidence: 0.84,
    frequency: 15,
    lat: 19.076,
    lon: 72.8777,
    description: "Western suburbs reporting intense showers. Local trains running delayed.",
    rainfallMm: 64,
  },
  {
    id: "i4",
    type: "Cyclone",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    minutesAgo: 12,
    status: "Verified",
    severity: "High",
    source: "APIs",
    aiConfidence: 0.76,
    frequency: 6,
    lat: 17.6868,
    lon: 83.2185,
    description: "Cyclonic circulation over west-central Bay of Bengal. Fishermen advised not to venture out.",
    rainfallMm: 48,
  },
  {
    id: "i5",
    type: "Heatwave",
    city: "Nagpur",
    state: "Maharashtra",
    minutesAgo: 18,
    status: "Unverified",
    severity: "Medium",
    source: "X (Twitter)",
    aiConfidence: 0.81,
    frequency: 10,
    lat: 21.1458,
    lon: 79.0882,
    description: "Daytime temperatures crossing 44°C. Heatwave warning issued for Vidarbha.",
  },
  {
    id: "i6",
    type: "Flood",
    city: "Kolkata",
    state: "West Bengal",
    minutesAgo: 22,
    status: "Under Review",
    severity: "High",
    source: "News",
    aiConfidence: 0.69,
    frequency: 4,
    lat: 22.5726,
    lon: 88.3639,
    description: "Waterlogging in Behala and Salt Lake after overnight downpour.",
    rainfallMm: 97,
  },
  {
    id: "i7",
    type: "Heavy Rain",
    city: "Chennai",
    state: "Tamil Nadu",
    minutesAgo: 25,
    status: "Verified",
    severity: "Medium",
    source: "X (Twitter)",
    aiConfidence: 0.87,
    frequency: 11,
    lat: 13.0827,
    lon: 80.2707,
    description: "Northeast monsoon active. Airport reporting delays due to poor visibility.",
    rainfallMm: 55,
  },
  {
    id: "i8",
    type: "Active Incident",
    city: "Guwahati",
    state: "Assam",
    minutesAgo: 32,
    status: "Verified",
    severity: "High",
    source: "Citizen Report",
    aiConfidence: 0.84,
    frequency: 7,
    lat: 26.1445,
    lon: 91.7362,
    description: "Brahmaputra water level above danger mark. Relief camps opened in Kamrup.",
    rainfallMm: 118,
  },
  {
    id: "i9",
    type: "Heavy Rain",
    city: "Bengaluru",
    state: "Karnataka",
    minutesAgo: 41,
    status: "Verified",
    severity: "Low",
    source: "APIs",
    aiConfidence: 0.9,
    frequency: 5,
    lat: 12.9716,
    lon: 77.5946,
    description: "Evening showers across south Bengaluru. Mild waterlogging on Outer Ring Road.",
    rainfallMm: 28,
  },
  {
    id: "i10",
    type: "Heatwave",
    city: "Delhi",
    state: "Delhi",
    minutesAgo: 50,
    status: "Verified",
    severity: "Medium",
    source: "News",
    aiConfidence: 0.93,
    frequency: 9,
    lat: 28.6139,
    lon: 77.209,
    description: "IMD heatwave watch for NCR. Hydration camps set up at major metro stations.",
  },
  {
    id: "i11",
    type: "Flood",
    city: "Cachar",
    state: "Assam",
    minutesAgo: 63,
    status: "Under Review",
    severity: "High",
    source: "Citizen Report",
    aiConfidence: 0.77,
    frequency: 3,
    lat: 24.8333,
    lon: 92.7789,
    description: "Barak river overflowing. Several villages cut off in Cachar district.",
    rainfallMm: 160,
  },
  {
    id: "i12",
    type: "Cyclone",
    city: "Puri",
    state: "Odisha",
    minutesAgo: 78,
    status: "Verified",
    severity: "High",
    source: "APIs",
    aiConfidence: 0.86,
    frequency: 8,
    lat: 19.8135,
    lon: 85.8312,
    description: "Cyclone watch along Odisha coast. NDRF teams pre-positioned at Puri and Ganjam.",
  },
  {
    id: "i13",
    type: "Heavy Rain",
    city: "Kochi",
    state: "Kerala",
    minutesAgo: 90,
    status: "Verified",
    severity: "Medium",
    source: "News",
    aiConfidence: 0.8,
    frequency: 6,
    lat: 9.9312,
    lon: 76.2673,
    description: "Orange alert for Ernakulam. Landslide-prone stretches on NH 66 closed.",
    rainfallMm: 72,
  },
  {
    id: "i14",
    type: "Active Incident",
    city: "Lucknow",
    state: "Uttar Pradesh",
    minutesAgo: 110,
    status: "Unverified",
    severity: "Low",
    source: "X (Twitter)",
    aiConfidence: 0.61,
    frequency: 2,
    lat: 26.8467,
    lon: 80.9462,
    description: "Unconfirmed reports of waterlogging near Gomti Nagar after brief squall.",
  },
  {
    id: "i15",
    type: "Heavy Rain",
    city: "Hyderabad",
    state: "Telangana",
    minutesAgo: 135,
    status: "Verified",
    severity: "Medium",
    source: "APIs",
    aiConfidence: 0.89,
    frequency: 7,
    lat: 17.385,
    lon: 78.4867,
    description: "IMD yellow alert. Hussain Sagar catchment recording 40 mm in 3 hours.",
    rainfallMm: 40,
  },
];

export const REPORTS: ReportRow[] = [
  {
    id: "r1",
    datetime: "Apr 30, 2025 10:42 AM",
    location: "Jaipur, Rajasthan",
    city: "Jaipur",
    state: "Rajasthan",
    event: "Heavy Rain",
    source: "X (Twitter)",
    aiConfidence: 0.92,
    status: "Verified",
    frequency: 12,
    severity: "High",
    text: "Heavy rain continues in Jaipur since morning. Roads are waterlogged and traffic is moving slow. #Jaipur #Rain #Weather",
    image: RAIN_IMG,
    likes: 124,
    comments: 302,
    shares: 1100,
    handle: "@weather_updates",
  },
  {
    id: "r2",
    datetime: "Apr 30, 2025 10:38 AM",
    location: "Patna, Bihar",
    city: "Patna",
    state: "Bihar",
    event: "Flood",
    source: "News",
    aiConfidence: 0.88,
    status: "Under Review",
    frequency: 8,
    severity: "High",
    text: "Ganga water level at Gandhi Ghat crosses the danger mark. District administration issues evacuation advisory.",
    image: FLOOD_IMG,
    likes: 88,
    comments: 41,
    shares: 210,
  },
  {
    id: "r3",
    datetime: "Apr 30, 2025 10:32 AM",
    location: "Mumbai, Maharashtra",
    city: "Mumbai",
    state: "Maharashtra",
    event: "Heavy Rain",
    source: "X (Twitter)",
    aiConfidence: 0.84,
    status: "Verified",
    frequency: 15,
    severity: "Medium",
    text: "Andheri subway flooded again. BEST buses diverted. Commuters stranded since 9 AM.",
    image: FLOOD2_IMG,
    likes: 540,
    comments: 190,
    shares: 860,
    handle: "@mumbaileaks",
  },
  {
    id: "r4",
    datetime: "Apr 30, 2025 10:25 AM",
    location: "Visakhapatnam, Andhra Pradesh",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    event: "Cyclone",
    source: "APIs",
    aiConfidence: 0.76,
    status: "Under Review",
    frequency: 6,
    severity: "High",
    text: "IMD: Cyclonic circulation over west-central Bay. Wind speeds 70-80 kmph gusting to 90 kmph along Vizag coast.",
    image: STORM_IMG,
    likes: 76,
    comments: 22,
    shares: 140,
  },
  {
    id: "r5",
    datetime: "Apr 30, 2025 10:18 AM",
    location: "Nagpur, Maharashtra",
    city: "Nagpur",
    state: "Maharashtra",
    event: "Heatwave",
    source: "X (Twitter)",
    aiConfidence: 0.81,
    status: "Verified",
    frequency: 10,
    severity: "Medium",
    text: "44.6°C at 2 PM in Nagpur. Schools asked to adjust timings. Carry water if you step out.",
    image: HEAT_IMG,
    likes: 210,
    comments: 54,
    shares: 97,
    handle: "@vidarbhaweather",
  },
  {
    id: "r6",
    datetime: "Apr 30, 2025 10:12 AM",
    location: "Kolkata, West Bengal",
    city: "Kolkata",
    state: "West Bengal",
    event: "Flood",
    source: "News",
    aiConfidence: 0.69,
    status: "Unverified",
    frequency: 4,
    severity: "High",
    text: "Unconfirmed videos of waist-deep water in Behala circulating on social media.",
    image: FLOOD_IMG,
    likes: 33,
    comments: 18,
    shares: 40,
  },
  {
    id: "r7",
    datetime: "Apr 30, 2025 10:05 AM",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    event: "Heavy Rain",
    source: "X (Twitter)",
    aiConfidence: 0.87,
    status: "Verified",
    frequency: 11,
    severity: "Medium",
    text: "Airport visibility down to 800 m. Two flights diverted to Bengaluru.",
    image: RAIN_IMG,
    likes: 410,
    comments: 88,
    shares: 260,
    handle: "@chennairains",
  },
  {
    id: "r8",
    datetime: "Apr 30, 2025 09:55 AM",
    location: "Guwahati, Assam",
    city: "Guwahati",
    state: "Assam",
    event: "Active Incident",
    source: "Citizen Report",
    aiConfidence: 0.84,
    status: "Verified",
    frequency: 7,
    severity: "High",
    text: "Need boats near Fancy Bazar. Water entered ground floor shops. Family of 6 stranded.",
    image: FLOOD2_IMG,
    likes: 19,
    comments: 41,
    shares: 73,
  },
  {
    id: "r9",
    datetime: "Apr 30, 2025 09:45 AM",
    location: "Ranchi, Jharkhand",
    city: "Ranchi",
    state: "Jharkhand",
    event: "Heavy Rain",
    source: "X (Twitter)",
    aiConfidence: 0.82,
    status: "Under Review",
    frequency: 5,
    severity: "Medium",
    text: "Continuous rain since midnight. Several trees uprooted on Harmu Road.",
    image: RAIN_IMG,
    likes: 61,
    comments: 14,
    shares: 22,
  },
  {
    id: "r10",
    datetime: "Apr 30, 2025 09:32 AM",
    location: "Bengaluru, Karnataka",
    city: "Bengaluru",
    state: "Karnataka",
    event: "Flood",
    source: "News",
    aiConfidence: 0.78,
    status: "Verified",
    frequency: 3,
    severity: "Low",
    text: "Bellandur lake overflow watch. Mild flooding on Sarjapur stretch.",
    image: FLOOD_IMG,
    likes: 150,
    comments: 29,
    shares: 44,
  },
];

export const STATE_ACTIVITY = [
  { state: "Uttar Pradesh", pct: 18, total: 224 },
  { state: "Maharashtra", pct: 16, total: 199 },
  { state: "Bihar", pct: 12, total: 150 },
  { state: "Tamil Nadu", pct: 10, total: 124 },
  { state: "Rajasthan", pct: 8, total: 98 },
  { state: "West Bengal", pct: 7, total: 87 },
  { state: "Gujarat", pct: 6, total: 74 },
  { state: "Others", pct: 23, total: 292 },
];

const HANDLES = [
  "@weather_updates",
  "@imd_pune",
  "@monsoonwatch",
  "@cityfloods",
  "@ndmaindia",
  "@skymet",
  "@localreporter",
  "@citizen_sos",
];
const AUTHORS = [
  "Weather Desk",
  "Ananya Rao",
  "Rahul Mehta",
  "IMD Nowcasting",
  "Priya Nair",
  "Arjun Das",
  "Kavita Singh",
  "Citizen Reporter",
];
const PLATFORMS: SocialPost["platform"][] = ["X", "News", "Citizen", "API", "Facebook", "YouTube"];

const POST_TEMPLATES: { text: string; event: EventType; loc: string; state: string; kw: string[] }[] = [
  {
    text: "Heavy rain continues in Jaipur since morning. Roads are waterlogged and traffic is moving slow. #Jaipur #Rain",
    event: "Heavy Rain",
    loc: "Jaipur",
    state: "Rajasthan",
    kw: ["rain", "waterlogging", "traffic"],
  },
  {
    text: "Water entered our ground floor in Patna. Need boats near Gandhi Maidan. #BiharFloods",
    event: "Flood",
    loc: "Patna",
    state: "Bihar",
    kw: ["flood", "boats", "rescue"],
  },
  {
    text: "Mumbai locals delayed on Western line after intense showers at Andheri. #MumbaiRains",
    event: "Heavy Rain",
    loc: "Mumbai",
    state: "Maharashtra",
    kw: ["rain", "trains", "delay"],
  },
  {
    text: "Cyclone alert for Vizag coast. Fishermen asked to return immediately. Winds 80 kmph.",
    event: "Cyclone",
    loc: "Visakhapatnam",
    state: "Andhra Pradesh",
    kw: ["cyclone", "winds", "fishermen"],
  },
  {
    text: "44°C in Nagpur right now. Please check on elderly neighbours. #Heatwave",
    event: "Heatwave",
    loc: "Nagpur",
    state: "Maharashtra",
    kw: ["heatwave", "temperature"],
  },
  {
    text: "Salt Lake Sector V streets under 2 feet of water. Office-goers stranded.",
    event: "Flood",
    loc: "Kolkata",
    state: "West Bengal",
    kw: ["flood", "waterlogging"],
  },
  {
    text: "Chennai airport reporting low visibility. Two arrivals diverted.",
    event: "Heavy Rain",
    loc: "Chennai",
    state: "Tamil Nadu",
    kw: ["rain", "airport", "visibility"],
  },
  {
    text: "Brahmaputra above danger level at Guwahati. Relief camps opening in Kamrup metro.",
    event: "Active Incident",
    loc: "Guwahati",
    state: "Assam",
    kw: ["flood", "relief", "river"],
  },
  {
    text: "IMD yellow warning for Hyderabad till 8 PM. Avoid underpasses.",
    event: "Heavy Rain",
    loc: "Hyderabad",
    state: "Telangana",
    kw: ["warning", "rain"],
  },
  {
    text: "Tree uprooted on MG Road, Bengaluru after a sudden squall. Traffic diverted.",
    event: "Active Incident",
    loc: "Bengaluru",
    state: "Karnataka",
    kw: ["squall", "tree", "traffic"],
  },
  {
    text: "Puri beach closed. NDRF teams on standby as the system intensifies over the Bay.",
    event: "Cyclone",
    loc: "Puri",
    state: "Odisha",
    kw: ["cyclone", "NDRF", "bay"],
  },
  {
    text: "Is this video of flooded Delhi roads from today or last year? Looks recycled. #FactCheck",
    event: "Flood",
    loc: "Delhi",
    state: "Delhi",
    kw: ["flood", "factcheck", "video"],
  },
  {
    text: "Light drizzle in Kochi but hill districts on orange alert. Landslide watch on NH 66.",
    event: "Heavy Rain",
    loc: "Kochi",
    state: "Kerala",
    kw: ["rain", "landslide", "alert"],
  },
  {
    text: "Citizen report: waterlogging near Gomti Nagar, Lucknow after 40 min downpour.",
    event: "Heavy Rain",
    loc: "Lucknow",
    state: "Uttar Pradesh",
    kw: ["rain", "citizen", "waterlogging"],
  },
  {
    text: "API ingest: rainfall 62 mm / 3h recorded at Santacruz observatory.",
    event: "Heavy Rain",
    loc: "Mumbai",
    state: "Maharashtra",
    kw: ["rainfall", "observatory", "API"],
  },
];

function rand<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}
function uid() {
  return Math.random().toString(36).slice(2, 10);
}

export function makeSocialPost(agoMs = 0): SocialPost {
  const t = rand(POST_TEMPLATES);
  const platform = rand(PLATFORMS);
  const ai = 0.62 + Math.random() * 0.36;
  const fake = Math.random() < 0.18 ? 0.35 + Math.random() * 0.5 : Math.random() * 0.22;
  const dup = Math.random() * 0.4;
  const trust = Math.min(0.99, Math.max(0.35, ai - fake * 0.4 + (Math.random() - 0.5) * 0.08));
  const status: VerificationStatus =
    trust > 0.82 ? "Verified" : trust > 0.62 ? "Under Review" : "Unverified";
  const severity: Severity = t.event === "Cyclone" || t.event === "Flood" ? "High" : Math.random() > 0.5 ? "Medium" : "Low";
  const sentiments: SocialPost["sentiment"][] = ["Urgent", "Negative", "Neutral", "Positive"];
  return {
    id: uid(),
    platform,
    author: rand(AUTHORS),
    handle: rand(HANDLES),
    text: t.text,
    location: t.loc,
    state: t.state,
    eventType: t.event,
    aiScore: Number(ai.toFixed(2)),
    fakeScore: Number(fake.toFixed(2)),
    duplicateScore: Number(dup.toFixed(2)),
    trustScore: Number(trust.toFixed(2)),
    sentiment: t.event === "Flood" || t.event === "Cyclone" ? "Urgent" : rand(sentiments),
    severity,
    status,
    timestamp: Date.now() - agoMs,
    keywords: t.kw,
    classified: t.event,
  };
}

export function seedSocialFeed(n = 18): SocialPost[] {
  return Array.from({ length: n }, (_, i) => makeSocialPost((i + 1) * 1000 * (20 + Math.random() * 80)));
}

export function formatAgo(ts: number): string {
  const s = Math.max(1, Math.round((Date.now() - ts) / 1000));
  if (s < 60) return `${s}s ago`;
  const m = Math.round(s / 60);
  if (m < 60) return `${m} min ago`;
  const h = Math.round(m / 60);
  return `${h}h ago`;
}

export function minutesLabel(m: number): string {
  if (m < 60) return `${m} mins ago`;
  const h = Math.floor(m / 60);
  return `${h}h ${m % 60}m ago`;
}

export function jitter(base: number, pct = 0.04): number {
  const delta = base * pct;
  return Math.max(0, base + (Math.random() * 2 - 1) * delta);
}

export const PIPELINE_STAGES = [
  {
    id: "src",
    step: "1",
    title: "Data Sources",
    color: "from-emerald-500 to-emerald-600",
    accent: "#10b981",
    items: ["Social Media", "Weather APIs", "Websites / News", "Public Datasets", "Citizen App"],
  },
  {
    id: "ing",
    step: "2",
    title: "Ingestion Services",
    color: "from-orange-500 to-orange-600",
    accent: "#f97316",
    items: ["API Collectors", "Web Scrapers", "Citizen REST API", "Scheduled Collectors"],
  },
  {
    id: "kafka",
    step: "3",
    title: "Kafka (Message Broker)",
    color: "from-violet-500 to-violet-700",
    accent: "#7c3aed",
    items: ["raw-reports", "weather", "citizen", "news"],
  },
  {
    id: "flink",
    step: "4",
    title: "Stream Processing",
    color: "from-sky-500 to-blue-600",
    accent: "#0ea5e9",
    items: ["Clean", "Normalize", "Enrich", "Extract Location"],
  },
  {
    id: "ai",
    step: "5",
    title: "AI / ML Layer",
    color: "from-amber-500 to-yellow-600",
    accent: "#f59e0b",
    items: ["Event Classification", "Fake / Misleading Detection", "Duplicate Detection", "Trust Score", "Severity Detection"],
  },
  {
    id: "event",
    step: "6",
    title: "Event Engine",
    color: "from-teal-500 to-teal-700",
    accent: "#0d9488",
    items: ["Reports → Real Events"],
  },
  {
    id: "store",
    step: "7",
    title: "Storage",
    color: "from-slate-600 to-slate-800",
    accent: "#334155",
    items: ["MongoDB", "Cassandra"],
  },
  {
    id: "api",
    step: "8",
    title: "Backend APIs",
    color: "from-indigo-500 to-indigo-700",
    accent: "#6366f1",
    items: ["Node.js / Express", "RESTful APIs"],
  },
];
