import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{MapContainer,TileLayer,CircleMarker,Popup}from"react-leaflet";
import"leaflet/dist/leaflet.css";import"./styles.css";
const API=import.meta.env.VITE_API_URL||"https://national-big-data-project.onrender.com";
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const cities={Lucknow:{state:"Uttar Pradesh",latitude:26.8467,longitude:80.9462},Guwahati:{state:"Assam",latitude:26.1445,longitude:91.7362},Jaipur:{state:"Rajasthan",latitude:26.9124,longitude:75.7873},Delhi:{state:"Delhi",latitude:28.6139,longitude:77.2090},Mumbai:{state:"Maharashtra",latitude:19.076,longitude:72.8777}};
function Badge({status}){let s=(status||"pending").toLowerCase();const label=s==="unverified"?"FALSE / CONTRADICTED":s.toUpperCase();return <span className={`badge ${s}`}>{label}</span>}
function Card({t,v,s}){return <div className="card"><small>{t}</small><strong>{v}</strong><span>{s}</span></div>}
function Pipeline(){return <div className="pipeline">{[["01","INGEST","Social report"],["02","EXTRACT","Event + location"],["03","MATCH","IMD reference"],["04","VALIDATE","Evidence score"],["05","DECIDE","Incident status"]].map((x,i)=><React.Fragment key={x[0]}><div><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]}</small></div>{i<4&&<i>→</i>}</React.Fragment>)}</div>}
function App(){const[tab,setTab]=useState("overview"),[d,setD]=useState(),[social,setSocial]=useState([]),[selected,setSelected]=useState(null),[socialStats,setSocialStats]=useState({accepted:0,verified:0,probable:0,rejected:0,pending:0}),[validation,setValidation]=useState(null),[busy,setBusy]=useState(false),[sim,setSim]=useState([]),[auto,setAuto]=useState(false),[toast,setToast]=useState(null);
 async function load(){try{const [dash,sr,ss]=await Promise.all([fetch(API+"/api/dashboard").then(r=>r.json()),fetch(API+"/api/social-reports").then(r=>r.json()),fetch(API+"/api/social-stats").then(r=>r.json())]);setD(dash);setSocial(sr);setSocialStats(ss)}catch(e){setToast("Backend connection failed. Check FastAPI.")}}
 useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
 async function analyze(id){setSelected(id);setValidation(null);await fetch(API+`/api/social-reports/${id}/analyze`,{method:"POST"});const v=await fetch(API+`/api/validation/${id}/run`,{method:"POST"}).then(r=>r.json());setValidation(v);await load()}
 async function simulate(){setBusy(true);setSim([]);const r=await fetch(API+"/api/simulation/social",{method:"POST"}).then(x=>x.json());for(const stage of r.stage){setSim(x=>[...x,stage]);await sleep(500)}setBusy(false);analyze(r.report_id)}
 if(!d)return <div className="loading">Starting weather intelligence engine…</div>;
 const verified=socialStats.verified, probable=socialStats.probable, unverified=socialStats.rejected; const accepted=socialStats.accepted; const rejected=social.filter(x=>x.validation_status==="unverified"); const acceptedReports=social.filter(x=>x.validation_status!=="unverified");
 return <><header><div><div className="eyebrow">WEATHER INCIDENT INTELLIGENCE • MVP</div><h1>Social Reports → IMD Validation</h1><p>Ingest public weather reports, extract structured evidence, and validate each claim against IMD reference observations.</p></div><div className="online">● PIPELINE ONLINE</div></header><nav>{[["overview","Overview"],["social","📡 Social Ingestion"],["rejected","❌ Rejected Reports"],["validation","Validation Engine"],["map","Incident Map"],["architecture","How It Works"]].map(x=><button key={x[0]} onClick={()=>setTab(x[0])} className={tab===x[0]?"active":""}>{x[1]}</button>)}<button onClick={simulate} className="simulate">{busy?"PROCESSING…":"▶ RUN LIVE SIMULATION"}</button></nav>
 {toast&&<div className="toast">{toast}<button onClick={()=>setToast(null)}>×</button></div>}
 {tab==="overview"&&<main><Pipeline/>{busy&&<div className="processing"><div className="spinner"></div><div><b>Running intelligence pipeline</b><div className="stage-list">{sim.map((s,i)=><span key={i}>✓ {s}</span>)}</div></div></div>}<section className="cards"><Card t="Validated Reports" v={accepted} s="accepted into incident intelligence"/><Card t="Verified" v={verified} s="validated incidents"/><Card t="Probable" v={probable} s="needs review"/><Card t="Rejected" v={unverified} s="kept separately, excluded from stats"/><Card t="Reference Data" v={d.observations} s="weather observations"/></section><section className="grid2"><div className="panel"><h2>Recent Intelligence</h2>{acceptedReports.slice(0,5).map(r=><div className="feed" key={r.id}><div><b>{r.platform}</b><p>{r.text}</p><small>{r.city}, {r.state} • {r.author}</small></div><div><Badge status={r.validation_status}/>{r.validation_score&&<strong>{r.validation_score}/100</strong>}<button className="link" onClick={()=>analyze(r.id)}>Analyze</button></div></div>)}</div><div className="panel"><h2>Live validation logic</h2><div className="logic"><span>📡 Incoming social report</span><i>↓</i><span>🧠 Extract event + location</span><i>↓</i><span>🏛 Match IMD reference</span><i>↓</i><span>⚖ Score evidence</span><i>↓</i><span>🟢 Corroborated / 🟡 Partial / 🔴 False or Contradicted</span></div></div></section></main>}
 {tab==="social"&&<SocialIngestion social={social} onCreated={()=>{load();setToast("Report ingested. Validation completed automatically.")}} onAnalyze={analyze} selected={selected} auto={auto} setAuto={setAuto}/>} 
 {tab==="rejected"&&<RejectedReports reports={rejected} onAnalyze={analyze}/>}
 {tab==="validation"&&<Validation validation={validation} social={acceptedReports} analyze={analyze}/>} 
 {tab==="map"&&<main><section className="panel"><h2>🗺 Incident Map</h2><p className="muted">Markers show the validation state of incoming social reports.</p><div className="legend"><span>🟢 Verified</span><span>🟡 Probable</span><span>🔴 False / Contradicted</span><span>⚪ Pending</span></div><div className="map"><MapContainer center={[22.5,79]} zoom={4.6}><TileLayer attribution="&copy; OpenStreetMap" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{acceptedReports.map(r=><CircleMarker key={r.id} center={[r.latitude,r.longitude]} radius={9} pathOptions={{color:r.validation_status==="verified"?"#12b76a":r.validation_status==="unverified"?"#f04438":r.validation_status==="probable"?"#f79009":"#667085"}}><Popup><b>{r.city}</b><br/>{r.event_type||"Unanalyzed report"}<br/>Status: {r.validation_status}<br/>Score: {r.validation_score||"—"}</Popup></CircleMarker>)}</MapContainer></div></section></main>}
 {tab==="architecture"&&<main><section className="panel"><h2>How the Intelligence Workflow Works</h2><div className="arch">{[["📡","Social Media Ingestion","A public post or manually injected report enters the API as an unstructured observation."],["🧠","Information Extraction","The system identifies event type, location, severity and useful keywords."],["🏛","IMD Reference Match","The extracted location is matched to the nearest available IMD reference observation."],["⚖","Validation Engine","Numerical claims are directly compared with IMD/reference observations; material contradictions override generic similarity scores."],["🎯","Decision","The claim becomes verified, probable or unverified."],["🗺","Incident Intelligence","Validated incidents appear on the map and evidence view."]].map((x,i)=><div key={i}><b>{x[0]}</b><section><strong>{x[1]}</strong><p>{x[2]}</p></section>{i<5&&<i>↓</i>}</div>)}</div><div className="note"><b>Demo mode:</b> the ingestion UI behaves like a live connector, while the included social reports and IMD reference observations are controlled demo data. A production connector can replace the input layer.</div></section></main>}
 {validation&&<div className="modal" onClick={()=>setValidation(null)}><div className="modal-inner" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setValidation(null)}>×</button><ValidationDetail v={validation}/></div></div>}<footer>Weather Incident Intelligence MVP • Demonstration system • Prototype reference values are not official warnings</footer></>}
function SocialIngestion({social,onCreated,onAnalyze,selected,auto,setAuto}){const[text,setText]=useState(""),[platform,setPlatform]=useState("X / Public Report"),[author,setAuthor]=useState("@field_report"),[city,setCity]=useState("Lucknow"),[busy,setBusy]=useState(false),[message,setMessage]=useState(null);
 async function inject(e){e.preventDefault();if(!text.trim())return;setBusy(true);const c=cities[city];try{const res=await fetch(API+"/api/social-reports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({platform,author,text:text.trim(),city,state:c.state,latitude:c.latitude,longitude:c.longitude,reported_at:new Date().toISOString()})});const data=await res.json();if(!res.ok)throw new Error(data.detail||"Injection failed");setMessage({type:data.status,score:data.score});setText("");onCreated()}catch(err){setMessage({type:"error",score:err.message})}finally{setBusy(false)}}
 useEffect(()=>{if(!auto)return;const examples=["Heavy rainfall is causing waterlogging in Gomti Nagar, Lucknow.","250mm rainfall recorded in Lucknow today. Roads are badly flooded!","Very heavy rainfall around Guwahati, low areas are waterlogged.","Hailstorm reported in Jaipur with strong winds."];let i=0;const timer=setInterval(async()=>{const c=cities[city];const body={platform:"Live Demo Feed",author:"@auto_ingest",text:examples[i++%examples.length],city,state:c.state,latitude:c.latitude,longitude:c.longitude,reported_at:new Date().toISOString()};await fetch(API+"/api/social-reports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});onCreated()},9000);return()=>clearInterval(timer)},[auto,city]);
 return <main><section className="panel"><div className="section-head"><div><div className="eyebrow">LIVE DATA INGESTION</div><h2>📡 Social Media Weather Monitor</h2><p className="muted">Paste a public report to inject it into the pipeline. The backend automatically extracts and validates it. Rejected claims remain visible here and under Rejected Reports, but are excluded from validated statistics.</p></div><label className="toggle"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/><span></span> Auto-ingest demo feed</label></div><div className="ingest-grid"><form className="inject" onSubmit={inject}><h3>Manual Injection</h3><label>Platform<select value={platform} onChange={e=>setPlatform(e.target.value)}><option>X / Public Report</option><option>Public Community Feed</option><option>WhatsApp / Citizen Tip</option></select></label><label>Author<input value={author} onChange={e=>setAuthor(e.target.value)}/></label><label>Location<select value={city} onChange={e=>setCity(e.target.value)}>{Object.keys(cities).map(c=><option key={c}>{c}</option>)}</select></label><label>Incoming report<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Example: Heavy rain is flooding roads near Gomti Nagar, Lucknow..."/></label><button className="primary full" disabled={busy}>{busy?"INGESTING…":"📡 INGEST & AUTO-VALIDATE"}</button>{message&&<div className={`ingest-result ${message.type}`}><b>{message.type==="error"?"Injection error":"Report processed"}</b><span>{message.type==="error"?message.score:`${String(message.type).toUpperCase()} • ${message.score}/100`}</span></div>}</form><div><div className="live-header"><h3>Live Incoming Feed</h3><span className="live-dot">● LIVE • refreshes every 5s</span></div>{social.map(r=><div className="social-card" key={r.id}><div className="source">{r.platform}<span>{r.author}</span></div><h3>{r.text}</h3><div className="meta"><span>📍 {r.city}, {r.state}</span><span>🕒 {new Date(r.reported_at).toLocaleString()}</span><Badge status={r.validation_status}/></div><div className="report-footer"><span>{r.event_type||"Waiting for extraction"}{r.validation_score!=null&&` • ${r.validation_score}/100`}</span><button className="link" onClick={()=>onAnalyze(r.id)}>{selected===r.id?"ANALYZING…":"View Evidence"}</button></div></div>)}</div></div></section></main>}
function RejectedReports({reports,onAnalyze}){return <main><section className="panel"><div className="section-head"><div><div className="eyebrow">QUALITY CONTROL</div><h2>❌ Rejected Reports</h2><p className="muted">False or contradicted social-media claims are retained for auditability, but they never enter the validated incident statistics or incident map.</p></div><div className="card mini"><small>Rejected</small><strong>{reports.length}</strong><span>excluded from main statistics</span></div></div>{reports.length===0?<div className="empty">No rejected reports yet. Inject a deliberately incorrect claim to demonstrate the validation gate.</div>:reports.map(r=><div className="validation-row rejected-row" key={r.id}><div><b>{r.city}, {r.state}</b><p>{r.text}</p><small>{r.platform} • {r.author} • {new Date(r.reported_at).toLocaleString()}</small><p className="muted">{r.validation_reason||"Rejected by validation engine."}</p></div><Badge status={r.validation_status}/><strong>{r.validation_score!=null?r.validation_score+"/100":"—"}</strong><button className="primary" onClick={()=>onAnalyze(r.id)}>View Evidence</button></div>)}</section></main>}
function Validation({social,analyze}){return <main><section className="panel"><h2>⚖ Validation Engine</h2><p className="muted">Select a report to see how a social claim is compared with reference weather observations.</p>{social.map(r=><div className="validation-row" key={r.id}><div><b>{r.city}, {r.state}</b><p>{r.text}</p></div><Badge status={r.validation_status}/><strong>{r.validation_score?r.validation_score+"/100":"—"}</strong><button className="primary" onClick={()=>analyze(r.id)}>Run Validation</button></div>)}</section></main>}
function ValidationDetail({v}){return <><div className="result-head"><div><div className="eyebrow">VALIDATION RESULT</div><h2>{v.report?.city} — {v.event}</h2></div><div className="big-score">{v.score}<small>/ 100</small></div></div><Badge status={v.status}/><div className="evidence"><div className="evidence-card"><h3>📱 Social Report</h3><p className="quote">“{v.report?.text}”</p><small>{v.report?.platform} • {v.report?.author}</small><hr/><b>Extracted event</b><p>{v.event}</p><b>Severity</b><p>{v.severity}</p><b>Keywords</b><p>{(v.keywords||[]).join(" • ")||"None"}</p></div><div className="evidence-card"><h3>🏛 IMD / Reference Data</h3><p><b>Station:</b> {v.imd?.station||"—"}</p><p><b>Source:</b> {v.imd?.source||"—"}</p><p><b>Rainfall:</b> {v.imd?.rainfall??"—"} mm</p><p><b>Temperature:</b> {v.imd?.temperature??"—"}°C</p><p><b>Humidity:</b> {v.imd?.humidity??"—"}%</p><p><b>Wind:</b> {v.imd?.wind_speed??"—"} km/h</p></div></div><h3>Validation Breakdown</h3><div className="bars">{[["Location match",v.location_match],["Time match",v.time_match],["Event match",v.event_match],["Severity consistency",v.severity_match],["Source reliability",v.source_reliability]].map(x=><div key={x[0]}><label><span>{x[0]}</span><b>{x[1]??"—"}%</b></label><div className="bar"><i style={{width:`${x[1]||0}%`}}></i></div></div>)}</div><div className="reason"><b>Why this decision?</b><p>{v.reason}</p>{v.numeric_checks?.length>0&&<div className="numeric-checks">{v.numeric_checks.map(c=><div key={c.metric}><b>{c.metric.replace("_"," ").toUpperCase()}</b><span>Social: {c.claim} • IMD: {c.reference} • Difference: {c.difference}</span><strong>{c.verdict.toUpperCase()}</strong></div>)}</div>}</div></>}
createRoot(document.getElementById("root")).render(<App/>);
